export const SAVE_USER_INFO_OBJECT = "SAVE_USER_INFO_OBJECT";
export const UPDATE_USER_INFO_OBJECT = "UPDATE_USER_INFO_OBJECT";
export const SAVE_USER_DETAILS = "SAVE_USER_DETAILS";
export const UPDATE_USER_DETAILS = "UPDATE_USER_DETAILS";
