export const FILTER_TYPES = {
	ALL: "all",
	MAPPED: "mapped",
	UNMAPPED: "unmapped",
};
export const INTEGRATIONS_CONSTANTS = {
	USERMAPPING_REQUESTED: "USERMAPPING_REQUESTED",
	USERMAPPING_FETCHED: "USERMAPPING_FETCHED",
	USERMAPPING_FETCHED: "USERMAPPING_FETCHED",
};
