export const viewsnewConstants = {
	VIEWS_REQUESTED: "VIEWS_REQUESTED",
	VIEWS_FETCHED: "VIEWS_FETCHED",
	CLEAR_SCREENTAG_VIEWS: "CLEAR_SCREENTAG_VIEWS",
	PATCH_VIEW: "PATCH_VIEW",
	SET_LAYOUT_OPTION: "SET_LAYOUT_OPTION",
};
